name: translation_engine_deepl
description: ""
version: 0.0.1
homepage: https://github.com/biyidev/uni_translate

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: any
  uni_translate_client: ^0.0.1

dev_dependencies:
  test: ^1.0.0
