name: translation_engine_deepl
description: DeepL translation engine
version: 0.1.1
homepage: https://github.com/biyidev/uni_translate

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: any
  uni_translate_client: ^0.1.1

dev_dependencies:
  test: ^1.0.0
