name: translation_engine_google
description: ""
version: 0.1.0
homepage: https://github.com/biyidev/uni_translate

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: any
  http: any
  uni_translate_client: ^0.1.0

dev_dependencies:
  test: ^1.0.0
