name: translation_engine_iciba
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: any
  uni_translate_client: ^0.0.1

dev_dependencies:
  test: ^1.0.0
